[project]
name = "pyoptflight"
version = "0.3"
description = "Rocket trajectory optimizer"
readme = "README.md"
requires-python = ">=3.13.5"
dependencies = [
    "casadi>=3.7.0",
    "ipykernel>=6.29.5",
    "ipympl>=0.9.7",
    "krpc>=0.5.4",
    "matplotlib>=3.10.3",
    "numpy>=2.3.0",
    "pandas>=2.3.0",
    "plotly>=6.1.2",
    "scikit-image>=0.25.2",
    "scikit-learn>=1.7.0",
    "scipy>=1.15.3",
]
